# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('tipocliente', models.CharField(blank=True, max_length=15, null=True)),
                ('pais', models.CharField(blank=True, max_length=15, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=15, null=True)),
                ('zona', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('puntoventa', models.CharField(blank=True, max_length=15, null=True)),
                ('tipoproducto', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha', models.CharField(blank=True, max_length=15, null=True)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('mesnumero', models.CharField(blank=True, max_length=2, null=True)),
                ('mes', models.CharField(blank=True, max_length=15, null=True)),
                ('dia', models.CharField(blank=True, max_length=15, null=True)),
                ('semestre', models.CharField(blank=True, max_length=10, null=True)),
                ('trimestre', models.CharField(blank=True, max_length=10, null=True)),
                ('semana', models.CharField(blank=True, max_length=10, null=True)),
                ('diasemana', models.CharField(blank=True, max_length=10, null=True)),
                ('empleado', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidadventas', models.CharField(blank=True, max_length=10, null=True)),
                ('cantidadproductos', models.CharField(blank=True, max_length=10, null=True)),
                ('valorventa', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
