# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='excel',
            name='estado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='excel',
            name='archivo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='analisis.Archivo'),
            preserve_default=False,
        ),
    ]
