# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 17:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analisis', '0002_auto_20160916_0223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'Archivo', 'verbose_name_plural': 'Archivos'},
        ),
        migrations.AlterModelOptions(
            name='excel',
            options={'verbose_name': 'Dato', 'verbose_name_plural': 'Datos'},
        ),
        migrations.AddField(
            model_name='excel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
