# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analisis', '0003_auto_20160916_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
